
[[constraint]]
  branch = "master"
  name = "github.com/Clever/unique-port"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.0"

[[constraint]]
  name = "github.com/dfuentes/ddbsync"

[[constraint]]
  name = "github.com/willf/bitset"
